using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace Mini_Project
{
    public partial class About : Form
    {
        public About()
        {
            InitializeComponent();
        }

        string l1 = "Product Description: \n\nThis Product is designed to: \nThis system is built for fast data processing and bill generation for supermarket customers \nTo reduce time in calculation of Sales activities \nThe billing system consists of an sql database and effective front end designed in .net \nThe system also contains discounts on various products \nTo store large amount of data in the database which will reduce clumsiness \nTo reduce paper work so that users can spend more time on monitoring the Super - Market. \nTo maintain the stock details \nTo keep record of Daily transections \nTo make faster and secure methods of payments \n\nThe main reason to design and develop this system is \nto make operating process by eliminating the complex operations \nwhich may be performed by the user to complete the overall transactions \nor effort required to get any particular financial information. \nWith the help of this super market management software, \nany user without any technical knowledge will be able to operate the system. \nThis system will store information on various modules in its database.";
        string l2 = "Advantages: \n\n1) Secure Login and also Reset Password Securly \n2) Bill will be generated by adding items to cart \n3) Different payment methods will be there to make payment secuerly like: \ncard, online(Gpay), Cash payment \n4) There will be Inventory of the supermarket to maintain sufficient stock \n5) Customer accounts will be managed in the supermarkets database \n6) Daily Transections will be recorded for evidence.";
        string l3 = "Product Users: \n\n1) Manager as Admin to Manage the Supermarket \n\n2) Cashier as Supermarket Staff to Bill Customers.";
        string l4 = "Product Team: SYBCA Mini Project Team: 3 \n\n1) Roll no. 5 -> Joel - Project Manager and Developer \n\n2) Roll no. 11 -> Ophir - Product Owner and Developer \n\n3) Roll no. 3 -> Aniket - Developer \n\n4) Roll no. 8 -> Mujamil - Developer.";
        string l5 = "Technologies Used: \n\n1. .Net as front end. \n2. SQL Client Server for Database \n3. GitHub to work with Team Online. \n4. C# Programming Language \n\nSoftware Used: \n\n1.	Windows 10.\n2.	Visual studio 2015. \n3. GitHub Desktop App";
        string l6 = "Hardware Requirements \n\n•	Processor – Intel Core processor above Pentium IV \n•	Ram – 512 MB \n•	Hard Disk – 1 GB \n•	Monitor. \n•	Keyboard. \n•	Visual Studio";
        string l7 = "Contact Numbers And Emails \n\n1. Joel \n\n Contact: 9145057933 \nEmail: 1904018.stu@dmscollege.ac.in\n\n2. Ophir \n\n Contact: 7262906152 \nEmail: 1904020.stu@dmscollege.ac.in\n\n3. Aniket \n\n Contact: 9607472478 \nEmail: 1904004.stu@dmscollege.ac.in\n\n4. Mujamil \n\n Contact: 8806230404 \nEmail: 1904013.stu@dmscollege.ac.in";

        private void About_Load(object sender, EventArgs e)
        {
            label1.Visible = false;
            label2.Visible = false;
            label3.Visible = false;
            label4.Visible = false;
            label5.Visible = false;
            label6.Visible = false;
            label6.Visible = false;
            label8.Visible = true;

            pictureBox1.Visible = false;
            pictureBox2.Visible = false;
            pictureBox4.Visible = false;
            pictureBox5.Visible = false;
            pictureBox6.Visible = false;
            pictureBox7.Visible = false;
            pictureBox8.Visible = false;
            pictureBox10.Visible = true;
        }

        private void button1_Click(object sender, EventArgs e)
        {
            if (Login.user == "Manager")
            {
                Manager_Dashboard db = new Manager_Dashboard();
                this.Hide();
                db.Show();
            }
            else
            {
                StartUp sp = new StartUp();
                this.Hide();
                sp.Show();
            }
        }

        private void productDiscriptionToolStripMenuItem_Click(object sender, EventArgs e)
        {
            label1.Text = l1;
            label1.Visible = true;
            label2.Visible = false;
            label3.Visible = false;
            label4.Visible = false;
            label5.Visible = false;
            label6.Visible = false;
            label7.Visible = false;
            label8.Visible = false;

            pictureBox1.Visible = true;
            pictureBox2.Visible = false;
            pictureBox4.Visible = false;
            pictureBox5.Visible = false;
            pictureBox6.Visible = false;
            pictureBox7.Visible = false;
            pictureBox8.Visible = false;
            pictureBox10.Visible = false;
        }

        private void advantagesToolStripMenuItem_Click(object sender, EventArgs e)
        {
            label1.Visible = false;
            label2.Text = l2;
            label2.Visible = true;
            label3.Visible = false;
            label4.Visible = false;
            label5.Visible = false;
            label6.Visible = false;
            label7.Visible = false;
            label8.Visible = false;

            pictureBox1.Visible = false;
            pictureBox2.Visible = true;
            pictureBox4.Visible = false;
            pictureBox5.Visible = false;
            pictureBox6.Visible = false;
            pictureBox7.Visible = false;
            pictureBox8.Visible = false;
            pictureBox10.Visible = false;
        }

        private void usersToolStripMenuItem_Click(object sender, EventArgs e)
        {
            label1.Visible = false;
            label2.Visible = false;
            label3.Text = l3;
            label3.Visible = true;
            label4.Visible = false;
            label5.Visible = false;
            label6.Visible = false;
            label7.Visible = false;
            label8.Visible = false;

            pictureBox1.Visible = false;
            pictureBox2.Visible = false;
            pictureBox4.Visible = true;
            pictureBox5.Visible = false;
            pictureBox6.Visible = false;
            pictureBox7.Visible = false;
            pictureBox8.Visible = false;
            pictureBox10.Visible = false;
        }

        private void developersToolStripMenuItem_Click(object sender, EventArgs e)
        {
            label1.Visible = false;
            label2.Visible = false;
            label3.Visible = false;
            label4.Text = l4;
            label4.Visible = true;
            label5.Visible = false;
            label6.Visible = false;
            label7.Visible = false;
            label8.Visible = false;

            pictureBox1.Visible = false;
            pictureBox2.Visible = false;
            pictureBox4.Visible = false;
            pictureBox5.Visible = true;
            pictureBox6.Visible = false;
            pictureBox7.Visible = false;
            pictureBox8.Visible = false;
            pictureBox10.Visible = false;
        }

        private void technologiesAndSoftwaresUsedToolStripMenuItem_Click(object sender, EventArgs e)
        {
            label1.Visible = false;
            label2.Visible = false;
            label3.Visible = false;
            label4.Visible = false;
            label5.Text = l5;
            label5.Visible = true;
            label6.Visible = false;
            label7.Visible = false;
            label8.Visible = false;

            pictureBox1.Visible = false;
            pictureBox2.Visible = false;
            pictureBox4.Visible = false;
            pictureBox5.Visible = false;
            pictureBox6.Visible = false;
            pictureBox7.Visible = true;
            pictureBox8.Visible = false;
            pictureBox10.Visible = false;
        }

        private void systemRequirementsToolStripMenuItem_Click(object sender, EventArgs e)
        {
            label1.Visible = false;
            label2.Visible = false;
            label3.Visible = false;
            label4.Visible = false;
            label5.Visible = false;
            label6.Visible = true;
            label6.Text = l6;
            label7.Visible = false;
            label8.Visible = false;

            pictureBox1.Visible = false;
            pictureBox2.Visible = false;
            pictureBox4.Visible = false;
            pictureBox5.Visible = false;
            pictureBox6.Visible = true;
            pictureBox7.Visible = false;
            pictureBox8.Visible = false;
            pictureBox10.Visible = false;
        }

        private void contactDevelopersToolStripMenuItem_Click(object sender, EventArgs e)
        {
            label1.Visible = false;
            label2.Visible = false;
            label3.Visible = false;
            label4.Visible = false;
            label5.Visible = false;
            label6.Visible = false;
            label7.Text = l7;
            label7.Visible = true;
            label8.Visible = false;

            pictureBox1.Visible = false;
            pictureBox2.Visible = false;
            pictureBox4.Visible = false;
            pictureBox5.Visible = false;
            pictureBox6.Visible = false;
            pictureBox7.Visible = false;
            pictureBox8.Visible = true;
            pictureBox10.Visible = false;
        }

        private void toolStripMenuItem1_Click(object sender, EventArgs e)
        {
            label1.Visible = false;
            label2.Visible = false;
            label3.Visible = false;
            label4.Visible = false;
            label5.Visible = false;
            label6.Visible = false;
            label7.Visible = false;
            label8.Visible = true;

            pictureBox1.Visible = false;
            pictureBox2.Visible = false;
            pictureBox4.Visible = false;
            pictureBox5.Visible = false;
            pictureBox6.Visible = false;
            pictureBox7.Visible = false;
            pictureBox8.Visible = false;
            pictureBox10.Visible = true;
        }
    }
}
