using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace Mini_Project
{
    public partial class About : Form
    {
        public About()
        {
            InitializeComponent();
        }

        private void About_Load(object sender, EventArgs e)
        {
            label1.Text = "Product Discription: \n\nThis Product is designed to: \nThis system is built for fast data processing and bill generation for supermarket customers \nTo reduce time in calculation of Sales activities \nThe billing system consists of an sql database and effective front end designed in .net \nThe system also contains discounts on various products \nTo store large amount of data in the database which will reduce clumsiness \nTo reduce paper work so that users can spend more time on monitoring the Super - Market. \nTo maintain the stock details \nTo keep record of Daily transections \nTo make faster and secure methods of payments";
            label2.Text = "Advantages: \n\n1) Login or Register to have an account in supermarket database to get offers & Discounts \n2) Bill will be generated by adding items to cart \n3) Different payment methods will be there to make payment secuerly like: card, online(Gpay), Cash payment \n4) There will be Inventory of the supermarket to maintain sufficient stock \n5) Customer accounts will be managed in the supermarkets database \n6) Daily Transections will be recorded for evidence ";
            label3.Text = "Product Users: \n1) Manager as Admin to Manage the Supermarket \n2) Cashier as Supermarket Staff to Bill Customers";
            label4.Text = "Product Team: SYBCA Mini Project Team: 3 \n1) Joel - Project Manager and Developer \n2) Ophir - Product Owner and Developer \n3) Aniket - Developer \n4) Mujamil - Developer";
        }

        private void button1_Click(object sender, EventArgs e)
        {
            Manager_Dashboard db = new Manager_Dashboard();
            this.Hide();
            db.Show();
        }
    }
}
